DROP TABLE IF EXISTS Game;

CREATE TABLE Game
(
    id    INT AUTO_INCREMENT PRIMARY KEY,
    userA VARCHAR(250) NOT NULL,
    userB VARCHAR(250) NOT NULL,
    board VARCHAR(1000) NOT NULL,
    turn VARCHAR(5) NOT NULL
);